#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/xdg/menus/applications.menu /etc/xdg/menus/gnome-applications.menu 3.8.0-1ubuntu3~ gnome-menus -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/menus/gnome-settings.menu 3.0.1-3~ gnome-menus -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/xdg/menus/gnome-preferences.menu 2.24.2-1~ gnome-menus -- "$@"
# End automatically added section
